version : "3.8"
services:
  flaskapp:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - 80:5000
    depends_on:
      - "database"
    restart: "on-failure"
    
  database:
    image: "postgres:latest"
    restart: "on-failure"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    